### PR TITLE
Fix custom output and charts conflict error

### LINKED ISSUE #886: Output option with convert -c fails.
Hi there,

When using `kompose convert -c` with the `-o` option, the charts are created in the desired folder but the last step fails:
```
> kompose convert -c -o chart
kompose convert -c -o chart
INFO Kubernetes file "chart/service-service.yaml" created
INFO Kubernetes file "chart/service-deployment.yaml" created
WARN open docker-compose/templates/chart/service-service.yaml: no such file or directory
WARN open docker-compose/templates/chart/service-deployment.yaml: no such file or directory
INFO chart created in "./docker-compose/"
```

The resulting `docker-compose` folder lacks the template files:
```
> tree docker-compose
docker-compose
├── Chart.yaml
├── README.md
└── templates
```

It would be nice to be able to choose the name of the outputting directory rather than it being hardcoded to `docker-compose`.

Cheers,

Jun

### PR DESCRIPTION
**Pull request by hangyan**
fix #886 

@cdrage I didn't find a correct way to add test for  this change. So can you help me with this?

After this change, the logic now becomes:

assume there is a yaml in /tmp/a.yaml

* -c : results in /tmp/a/
* -c -o /tmp/charts : results in /tmp/charts/ (yaml in /tmp/charts/templates)
* -o /tmp/charts: results in /tmp/charts 
*  no args: results yaml in current dir

### CODE REVIEW

**Comment by cdrage** [comment]
To be honest @hangyan I don't think there are *any* tests written at the moment for charts. I'll review this soon however and test it out before we merge this in!

**Comment by hangyan** [comment]
@cdrage I have add some simple tests for charts and cutom output working together, I think it's enough for now

File: pkg/transformer/kubernetes/k8sutils.go [hunk 1]
```diff
@@ -200,14 +195,25 @@ func PrintList(objects []runtime.Object, opt kobject.ConvertOptions) error {
...
 			return errors.Wrap(err, "transformer.Print failed")
 		}
 		files = append(files, printVal)
 	} else {
+		finalDirName := dirName
+		if opt.CreateChart {
+			finalDirName = dirName + string(os.PathSeparator) + "templates"
+		}
+
+		log.Infof("YAML results in : %s", finalDirName)
```
Comment (cdrage) [inline pkg/transformer/kubernetes/k8sutils.go]: Is this suppose to be debug information?

Comment (cdrage) [reply pkg/transformer/kubernetes/k8sutils.go]: If not, it may be better to indicate that this is where the chart information will be :) For example: `Chart files located at: %s", finalDirName` or something along those lines.

Comment (hangyan) [reply pkg/transformer/kubernetes/k8sutils.go]: @cdrage updated, remove the debug information, thanks very much!

**Comment by cdrage** [comment]
Thanks so much for all these recent contributions! Tests pass and code LGTM :+1:

**Comment by hangyan** [comment]
@cdrage Glad that I can help, hoping to do more contribute to this greate project
